language: php
php:
  - 5.4

#script: phpunit --bootstrap tests/travis.php tests/unit/ --coverage-clover build/logs/clover.xml
script: phpunit --bootstrap tests/travis.php tests/unit/

#addons:
#  code_climate:
#    repo_token: 13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360

#after_script:
#  - CODECLIMATE_REPO_TOKEN=13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360 vendor/bin/test-reporter

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIHYND4WZVKBVMXVQ
  secret_access_key:
    secure: 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
    region: us-west-2a
  app: phpXelerator5
  env: phpxelerator5-env
  bucket_name: elasticbeanstalk-us-west-2-306034767610
  on:
    repo: https://github.com/giraldomauricio/phpXelerator5
    branch: master