language: php
php:
  - 5.4

#script: phpunit --bootstrap tests/travis.php tests/unit/ --coverage-clover build/logs/clover.xml
script: phpunit --bootstrap tests/travis.php tests/unit/

#addons:
#  code_climate:
#    repo_token: 13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360

#after_script:
#  - CODECLIMATE_REPO_TOKEN=13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360 vendor/bin/test-reporter

deploy:
  provider: elasticbeanstalk
  access_key_id: 
  secret_access_key:
    secure: 
    region: us-west-2a
  app: phpXelerator5
  env: phpxelerator5-env
  bucket_name: 
  on:
    repo: giraldomauricio/phpXelerator5
    branch: master
