language: php
php:
  - 5.4

#script: phpunit --bootstrap tests\\/travis.php tests\\/unit\\/ --coverage-clover build\\/logs\\/clover.xml
script: phpunit --bootstrap tests/travis.php tests/unit/

#addons:
#  code_climate:
#    repo_token: 13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360

#after_script:
#  - CODECLIMATE_REPO_TOKEN\\=13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360 vendor\\/bin\\/test-reporter

deploy:
  provider: elasticbeanstalk
  edge: true
  bucket_name: elasticbeanstalk-us-west-2-306034767610.s3-website-us-west-2.amazonaws.com
  app: phpXelerator5
  env: phpxelerator5-env
  region: us-west-2a
  access_key_id:
    secure: hGuSmPmUOAkVD0GFelD4po5kcwFfX9BMjNeQjf6YAwHNrcMW77oqybaz59qyhQMzJi3ITcFY3VI0FvZikD24NrvZQPay2kgRmUkw8WZhgQ2jnErat\\/mT4W5jbmROGGHTbZdiJsOgRoTDM4UFMevziKQj7o\\+RNXZQ9GK55rIAt522CYStWykevyRC3vlQ6PYu4uZMJhXrmVKDP7Bykx2miDKfU\\/3HO6sui0\\+tzLWTjvSZqw55z1o\\/ExfvkqzY4pCNL9nlNi2n7yAnQl5SrlW1uf0oUw\\/RokivhgsMIvSLyusCAu6bhYstXfPygabGVMJ2HHOkQP9KW0vd8ACx3wFgiuF77EJlSMFQ4C0c1WFTznamITwqelhGOdn\\+QT5xroF7CY7PCrN1RAOoCEqZNBgP1NbsPY0AFcOcRZweE4M5QLdAp0f\\+29Wew6P8v36moQfV1\\/0PpFvNyloCI47UjS0qw\\/nOOb1x\\/wm814RbG5mPmSg5Mm\\/\\+\\+DKCqfqgTujolwFBw7OA\\+wZDNpb\\/OnPBbvmbHqsobvBcBL4ptoZsSRnN18MwgMRiSUuPBmIJybc8yLuPiEzXcRimoH1t8qLKsYEZLjz57e3\\+4MhbLsyZ73lRmXU1VZGo7jWycGIlWld\\+yE9VG8omB3V\\/zDoB99NzrauMVo8cdb6YTw8x\\/RhdHNvGBXQ\\=
  secret_access_key:
    secure: TE0HreDSjPcc5RKG0\\+0t\\/5Q5DM8UXYgq2o1AG58Pe2qYjjlVsF8OjQarVqVGPX3omHthH\\+dynD3eyWD3odNy8CAB6c2VFosimqWT\\+NCoH52c6hiFdn0PJQrAXBYawXWF6XvA6\\/lrx5t44\\+t4I\\/rinX7xxHNau0PaqxzFEx58UQoiq36eZC5bMuc\\/rSXEGz82sw7imXDNSaviCiqrN5oESudZ2bDScCHIhrTLGk24sfWRx5KZG96rXrsFpmBa1SWgPH\\/Md1lrjc6UAGi\\+q0Fz3\\+gwdHCbBBPrajvpCN\\/UsbpIWoIKe9EIjVDrOSEsTFF1BtfAjxlJxZonuqEXymTtMqCWzhQqwDnzqjgJSkfBPGwwVRdPm6whC\\+dbVHkkSkME2a9r7pcb8PoRFgEo\\/OxNKIRoCBGpU1pWK1GXRsblog8wNSJDmipXaH2fzJFu4ik1chCs6nzk6C2tzfWQulyd5Bd0KHv0HL3iYg9OISxm3734K16\\+8yYEUYlzej6x5kyIbX\\/cFvk3N5dLChGPhzG6E3Gh5734TFbGRHP0i7cUaFfIFqVS8jiaA6E7TA\\/1AF7x7ZWSY6ffX9PulEw\\/kB50fJcIL8zWPrGhvNNbxFWGQSf6iMBY7Scv\\+hbyPFotFI9tMauLaOr0x\\/gwNR0D\\+9yuBTrDN34NiYKJJ6Q2wIGCOZo\\=
  skip_cleanup: true
  on:
    repo: giraldomauricio/phpXelerator5 
    branch: master
