language: php
php:
  - 5.4

#script: phpunit --bootstrap tests\\\\/travis.php tests\\\\/unit\\\\/ --coverage-clover build\\\\/logs\\\\/clover.xml
script: phpunit --bootstrap tests\\/travis.php tests\\/unit\\/

#addons:
#  code_climate:
#    repo_token: 13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360

#after_script:
#  - CODECLIMATE_REPO_TOKEN\\\\=13bcb9a98909533393b5d0297aaa66ade7eedc37deef440e85fe8bd573376360 vendor\\\\/bin\\\\/test-reporter

deploy:
  provider: s3
  bucket: elasticbeanstalk-us-west-2-306034767610
  access_key_id:
    secure: awZvk4dHUt0rIY2q\\/udYYPxQLa6pVgDpWHOvSkjg4eaze9yrdp0AuPILg3p5DKXrfO5SvwxUZVLt0eMmBDCvoZirobRgdwg7Sm\\+gQHOqj7hV\\/tltGVui0e5maITIky8zrX65WkHJmYierFca3V04w\\/ofaTtvnj7lQBStts9E8sVhq6IaLvvyLETmrj6vkvIzsCh14S9hkV9Y0Wdo3xS0dUlgP\\+eYRR0vfCarw\\/IJ54XfhQY0XxkBbddai3yNrZvoZimnXIkXuednKqN6YOt6njOPlhhTHCAqA9TT5c21NqT6EGPgYa3ncTUAm8saAxry6VaC8QRdAp\\/zfbxTVtnm2Uf3V4DdoXslARkljB6hSB5itEUZsd\\+aVWTpg\\/KqMiofGkQ4POFbS2XkocQJ3MnNIlNW\\/LnbPhqaDMJti8R3dyN1zIaBnu1XWO5PWCZwvYxwjl\\/LtzP0BPMUcJlTFlEOi7MvR61IgKyPonxWlWwxLtO0JMpSbd0kY31LV2JAKuioPQ4FpphA6Zkl7xdoO5oRX7\\+aQ4P3VvDII9zlQ1OgmueZfeW11cKFBkZxiEQbkrlr4MCZATPPSjg2v6N0JhnSz0Uluk7IZ4jdoy1Kk4ZdRXZlD92ELAF8RfCdWoSk2G1rxGJjapo\\/crUlf1pf0K\\+\\+RHpIZJYJIrwyRaCPC8JO6Qg\\=
  secret_access_key:
    secure: GG3pSBRxGHaNLZ0Kl\\+hNFpCIYUkKWqNwPc\\/qYnJRE26Bos\\/8EYqIjqjn1O8zJ1LiwQ6z2b4xEqgmWaTZdlAH3mS04hKrEC8ssI\\/062\\/zAluiWCo4BaqkkGb\\+n0yl43K5BUHGaiov2CtzG99Nk5FTikfz6Kf6etnu\\/3\\/yhNGfutEAv19f0HLWa9pM8oc03jXBai\\/2t9ENDfQiRKjPVipPThAFaSIy70mdh8ALDmyhUIIERCiQvrxZvGhUJC1zMohahq13EggVVw9L6Ths\\/UGddo5azQejQr5gNJLNq9zJjXZigEToqRjiEVFEYTok7T4qD8qNhz5qwPkMm7g6VLKtjMyq6drmRYWF4o1SLv\\+rjkdors\\+Iydn9lF39VC\\+ld7VtkWB7bHXQhykROF4AMXg20ZgMRWA29CT2tvfP4q7D5PTSxVDhTyHL7tx9sTX8qXw\\+0m\\+w\\+XTXoaSEt\\/au3Z0S5VBSj8Gqp5kZJfreh\\/YRbdeiFMxhYdTDod4Tn2cFXp\\+EBG1\\/LVdmHWvCEyJogAhXHT6N8rvh5EBfQNreGa9PHlGSSLA\\/dv2\\/RwcxqafwwROQsrbZcg4btJqAiRvZOIHozF\\+vPGfCSR9KeEEoyVza51KKN5ZTdsnQw\\+MXWxdGUVoKTgkydYciIe5ESA35b9esZNGSNJGZrv24AZPVtIw17Xk\\=